# mididemo needs the MIDI engine + sample voice engine from the SDK.
SDK_DIR = ../../sdk
SRCS = main.c \
       $(SDK_DIR)/of_midi.c \
       $(SDK_DIR)/of_smp_bank.c \
       $(SDK_DIR)/of_smp_voice.c \
       $(SDK_DIR)/of_smp_tables.c
include ../app.mk
