# openfpgaOS SDK — Build Rules
#
# This file is SDK-owned and is regenerated by the OS source tree's
# `make sdk DEST=...` target. Do not edit -- customize your build in
# your app's Makefile by setting CFLAGS / SRCS / SRCS_CXX before
# including this file.
#
# Standard library: apps statically link upstream musl 1.2.5 (bundled
# under $(SDK_DIR)/musl/). musl emits Linux RISC-V syscalls via ecall;
# the openfpgaOS kernel implements the small subset musl actually uses.
# openfpgaOS-specific subsystems (video, audio, mixer, GPU, ...) live
# in the SBI vendor extension space and are wrapped by the inline
# functions in $(SDK_DIR)/include/of_*.h.
#
# Entry point: musl's own crt1.o + __libc_start_main. The kernel ELF
# loader sets up the standard SysV ABI stack (argc/argv/envp), so
# musl's startup chain works without any custom CRT.
#

# ── Toolchain (auto-detect) ───────────────────────────────────────────
CROSS ?= $(shell which riscv64-unknown-elf-gcc >/dev/null 2>&1 && echo riscv64-unknown-elf- || echo riscv64-elf-)
CC      = $(CROSS)gcc
CXX     = $(CROSS)g++
LD      = $(CROSS)gcc
AS      = $(CROSS)gcc
OBJDUMP = $(CROSS)objdump
SIZE    = $(CROSS)size

# ── Architecture ──────────────────────────────────────────────────────
ARCH = rv32imafc
ABI  = ilp32f

# ── Paths ─────────────────────────────────────────────────────────────
SDK_DIR   ?= src/sdk
MUSL_DIR   = $(SDK_DIR)/musl
APP_LD    ?= $(SDK_DIR)/app.ld
BUILD_DIR ?= .
OBJ_DIR   ?= $(BUILD_DIR)

# musl crt objects -- crt1.o brings in _start, crti/crtn bracket
# .init/.fini for static constructors.
CRT_OBJS = $(MUSL_DIR)/lib/crt1.o $(MUSL_DIR)/lib/crti.o $(MUSL_DIR)/lib/crtn.o

# ── Common flags ─────────────────────────────────────────────────────
ARCH_FLAGS = -march=$(ARCH) -mabi=$(ABI)

# Includes: openfpgaOS headers + bundled musl headers, in that order so
# `#include "of.h"` and `#include <stdio.h>` both resolve. -nostdinc keeps
# the host system headers out of the search path entirely.
SDK_INCLUDES = -nostdinc \
               -I$(SDK_DIR)/include \
               -isystem $(MUSL_DIR)/include

# ── C compiler flags ─────────────────────────────────────────────────
SDK_CFLAGS  = $(ARCH_FLAGS) -O2 -Wall -Wextra -fdiagnostics-color=always
SDK_CFLAGS += -ffunction-sections -fdata-sections
# Cache-line align hot code so the I$ refill is one transaction.
SDK_CFLAGS += -falign-functions=64 -falign-loops=64
# Don't let GCC auto-rewrite plain loops as memset/memcpy calls -- musl
# provides those as real symbols, but the rewrite confuses LTO and the
# loader's relocation pass.
SDK_CFLAGS += -fno-tree-loop-distribute-patterns
SDK_CFLAGS += $(SDK_INCLUDES)

CFLAGS ?=
ALL_CFLAGS = $(SDK_CFLAGS) $(CFLAGS)

# ── C++ compiler flags ───────────────────────────────────────────────
SDK_CXXFLAGS  = $(ARCH_FLAGS) -O2 -Wall -Wextra -fdiagnostics-color=always
SDK_CXXFLAGS += -ffunction-sections -fdata-sections
SDK_CXXFLAGS += -fno-exceptions -fno-rtti
SDK_CXXFLAGS += -falign-functions=64 -falign-loops=64
SDK_CXXFLAGS += -fno-tree-loop-distribute-patterns
SDK_CXXFLAGS += $(SDK_INCLUDES)

CXXFLAGS ?=
ALL_CXXFLAGS = $(SDK_CXXFLAGS) $(CXXFLAGS)

# ── Linker flags ─────────────────────────────────────────────────────
# -nostdlib: don't pull in host libc (we link musl explicitly).
# -static:   no dynamic linking (kernel loader is static-only).
# -T:        use the openfpgaOS app linker script (places code at the
#            address the loader expects, sets up BRAM hot-text section).
SDK_LDFLAGS  = $(ARCH_FLAGS)
SDK_LDFLAGS += -nostdlib -static
SDK_LDFLAGS += -T $(APP_LD)
SDK_LDFLAGS += -L$(MUSL_DIR)/lib
SDK_LDFLAGS += -Wl,--gc-sections -Wl,--no-warn-rwx-segments

LDFLAGS ?=
ALL_LDFLAGS = $(SDK_LDFLAGS) $(LDFLAGS)

ASFLAGS = $(ARCH_FLAGS)

# Compiler runtime helpers (__divdi3, __floatsisf, soft-float helpers).
LIBGCC = $(shell $(CC) $(ARCH_FLAGS) -print-libgcc-file-name)

# musl + math + libgcc, in the order the linker wants. We deliberately
# don't pull in the toolchain's libsupc++ -- it was built against newlib
# and references newlib-only symbols (_impure_ptr, _Unwind_Resume, ...)
# that musl doesn't ship. C++ apps link the SDK's own minimal C++ ABI
# shim ($(OF_CXXABI_SRC)) instead.
LIBS = -Wl,--start-group -lc -lm -lgcc -Wl,--end-group

# ── Optional SDK helper sources ──────────────────────────────────────
# Apps that need a particular subsystem can opt in by appending one of
# these variables to SRCS / SRCS_CXX in their own Makefile, e.g.:
#     SRCS     = main.c $(OF_MIDI_SRC)
#     SRCS_CXX = main.cpp $(OF_CXXABI_SRC)
OF_MIDI_SRC   = $(SDK_DIR)/of_midi.c
OF_CXXABI_SRC = $(SDK_DIR)/of_cxxabi.cpp

# ── Sources / objects ────────────────────────────────────────────────
SRCS_CXX ?=
APP_C_OBJS   = $(patsubst %.c,$(OBJ_DIR)/%.o,$(filter %.c,$(SRCS)))
APP_CXX_OBJS = $(patsubst %.cpp,$(OBJ_DIR)/%.o,$(filter %.cpp,$(SRCS_CXX)))
APP_OBJS     = $(APP_C_OBJS) $(APP_CXX_OBJS)

# ── Pocket build ─────────────────────────────────────────────────────
$(BUILD_DIR)/app.elf: $(APP_OBJS) $(APP_LD) $(CRT_OBJS)
	@mkdir -p $(dir $@)
	$(LD) $(ALL_LDFLAGS) -o $@ $(CRT_OBJS) $(APP_OBJS) $(LIBS)

$(OBJ_DIR)/%.o: %.c
	@mkdir -p $(dir $@)
	$(CC) $(ALL_CFLAGS) -c -o $@ $<

$(OBJ_DIR)/%.o: %.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(ALL_CXXFLAGS) -c -o $@ $<

# ── PC build (SDL2) ──────────────────────────────────────────────────
PC_CC ?= cc
SDL_CFLAGS := $(shell sdl2-config --cflags 2>/dev/null || pkg-config --cflags sdl2 2>/dev/null)
SDL_LIBS   := $(shell sdl2-config --libs 2>/dev/null || pkg-config --libs sdl2 2>/dev/null)

app_pc: $(SRCS) $(SDK_DIR)/pc/of_sdl2.c $(SDK_DIR)/include/of.h
	$(PC_CC) -DOF_PC -I$(SDK_DIR)/include -I. -O2 -Wall -Wextra \
		$(SRCS) $(SDK_DIR)/pc/of_sdl2.c \
		$(SDL_CFLAGS) $(SDL_LIBS) -lm -o $@

# ── Clean ────────────────────────────────────────────────────────────
sdk-clean:
	rm -f $(APP_OBJS) $(BUILD_DIR)/app.elf app_pc
	@if [ "$(OBJ_DIR)" != "." ] && [ -d "$(OBJ_DIR)" ]; then rm -rf "$(OBJ_DIR)"; fi
